source 'https://rubygems.org'

gem 'rbattlenet', git: "git://github.com/emielvanlankveld/rbattlenet.git", branch: 'api-migration'
gem 'mysql2'
gem 'typhoeus'
gem 'sequel'
gem 'aws-sdk'
gem 'tzinfo'
gem 'require_all'
gem 'byebug'
gem 'arangorb'
gem 'rollbar'
