apiVersion: apps/v1
kind: Deployment
metadata:
  name: blizzard-deployment-acc
  labels:
    app: blizzard-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blizzard-acc
  template:
    metadata:
      labels:
        app: blizzard-acc
        metrics: wowaudit-scraper
    spec:
      containers:
        - name: blizzard-acc
          image: shedi/wowaudit-acc:latest
          command: ["/srv/bin/refresh"]
          args: ["blizzard"]

          ports:
            - name: metrics
              containerPort: 9394

          resources:
            requests:
              cpu: 250m
              memory: 400Mi

            limits:
              cpu: 1000m
              memory: 850Mi

      imagePullSecrets:
        - name: regcred
