apiVersion: apps/v1
kind: Deployment
metadata:
  name: blizzard-deployment
  labels:
    app: blizzard
spec:
  replicas: 8
  selector:
    matchLabels:
      app: blizzard
  template:
    metadata:
      labels:
        app: blizzard
        metrics: wowaudit-scraper
    spec:
      containers:
        - name: blizzard
          image: shedi/wowaudit:latest
          command: ["/srv/bin/refresh"]
          args: ["blizzard"]

          ports:
            - name: metrics
              containerPort: 9394

          resources:
            requests:
              cpu: 250m
              memory: 300Mi

            limits:
              cpu: 1000m
              memory: 2000Mi

      imagePullSecrets:
        - name: regcred
