apiVersion: apps/v1
kind: Deployment
metadata:
  name: blizzard-deployment-acc
  labels:
    app: blizzard-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blizzard-acc
  template:
    metadata:
      labels:
        app: blizzard-acc
    spec:
      tolerations:
        - key: low-performance-node
          operator: Exists
          effect: NoSchedule
      containers:
        - name: blizzard-acc
          image: shedi/wowaudit-acc:latest
          command: ["/srv/bin/refresh"]
          args: ["blizzard"]

          resources:
            requests:
              cpu: 250m
              memory: 400Mi

            limits:
              cpu: 250m
              memory: 750Mi

      imagePullSecrets:
        - name: regcred
