apiVersion: apps/v1
kind: Deployment
metadata:
  name: historical-keystones-deployment-acc
  labels:
    app: historical-keystones-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historical-keystones-acc
  template:
    metadata:
      labels:
        app: historical-keystones-acc
    spec:
      tolerations:
        - key: migrate-data
          operator: Exists
          effect: NoSchedule
      containers:
        - name: historical-keystones-acc
          image: shedi/wowaudit:latest
          command: ["/srv/bin/refresh"]
          args: ["historical_keystones"]

          resources:
            requests:
              cpu: 250m
              memory: 1000Mi

            limits:
              memory: 1500Mi

      imagePullSecrets:
        - name: regcred
