apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystones-deployment-acc
  labels:
    app: keystones-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keystones-acc
  template:
    metadata:
      labels:
        app: keystones-acc
    spec:
      tolerations:
        - key: low-performance-node
          operator: Exists
          effect: NoSchedule
      containers:
        - name: keystones-acc
          image: shedi/wowaudit-acc:latest
          command: ["/srv/bin/refresh"]
          args: ["keystones"]

          resources:
            requests:
              cpu: 750m
              memory: 2000Mi

            limits:
              memory: 5000Mi

      imagePullSecrets:
        - name: regcred
