apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment-acc
  labels:
    app: scheduler-acc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-acc
  template:
    metadata:
      labels:
        app: scheduler-acc
    spec:
      tolerations:
        - key: migrate-data
          operator: Exists
          effect: NoSchedule
      containers:
        - name: scheduler-acc
          image: shedi/wowaudit-acc:latest
          command: ["/srv/bin/schedule"]

          resources:
            requests:
              cpu: 50m
              memory: 250Mi

            limits:
              memory: 500Mi

      imagePullSecrets:
        - name: regcred
