apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcl-deployment-acc
  labels:
    app: wcl-acc
spec:
  replicas: 0
  selector:
    matchLabels:
      app: wcl-acc
  template:
    metadata:
      labels:
        app: wcl-acc
    spec:
      tolerations:
        - key: low-performance-node
          operator: Exists
          effect: NoSchedule
      containers:
        - name: wcl-acc
          image: shedi/wowaudit-acc:latest
          command: ["/srv/bin/refresh"]
          args: ["wcl"]

          resources:
            requests:
              cpu: 50m
              memory: 250Mi

            limits:
              memory: 500Mi

      imagePullSecrets:
        - name: regcred
